//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppRelease
    {
        public int AppReleaseId { get; set; }
        public string Android_Url { get; set; }
        public string Android_Latest_Version { get; set; }
        public bool Android_Update_Flag { get; set; }
        public string iOS_Url { get; set; }
        public string iOS_Latest_Version { get; set; }
        public bool iOS_Update_Flag { get; set; }
    }
}
