//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseData
    {
        public int BaseDateId { get; set; }
        public string APIPath { get; set; }
        public string SmsApiPath { get; set; }
        public string VXpressLoginPath { get; set; }
        public string PaynimoLoginPath { get; set; }
        public string VXPressUserName { get; set; }
        public string VXPressPassword { get; set; }
        public string PaynimoUserName { get; set; }
        public string PaynimoPassword { get; set; }
    }
}
