//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Board_Mapping_Standard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Board_Mapping_Standard()
        {
            this.Package_Mapping_BoardStandard = new HashSet<Package_Mapping_BoardStandard>();
            this.Product_Mapping_BoardStandard = new HashSet<Product_Mapping_BoardStandard>();
        }
    
        public int BoardMappingStandardId { get; set; }
        public int BoardId { get; set; }
        public int StandardId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int DeleteStatus { get; set; }
    
        public virtual Board Board { get; set; }
        public virtual Standard Standard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Package_Mapping_BoardStandard> Package_Mapping_BoardStandard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Mapping_BoardStandard> Product_Mapping_BoardStandard { get; set; }
    }
}
