//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart_Paackage_Mapping_Product
    {
        public int Cart_Paackage_Mapping_Productid { get; set; }
        public int AddCartId { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public bool IsSelected { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int DeleteStatus { get; set; }
    }
}
