//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public int CouponId { get; set; }
        public int CouponTypeId { get; set; }
        public string CouponCode { get; set; }
        public string CouponTitle { get; set; }
        public string CoupounDescription { get; set; }
        public decimal MinOrderAmount { get; set; }
        public decimal MaxOrderAmount { get; set; }
        public decimal OfferAmount { get; set; }
        public decimal OfferPercentage { get; set; }
        public int ReedemCount { get; set; }
        public int CouponLeftCount { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int DeleteStatus { get; set; }
    }
}
