//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon_Mapping_Order
    {
        public int Coupon_Mapping_OrderId { get; set; }
        public int CouponId { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public decimal OrderAmount { get; set; }
        public int ProductsInOrder { get; set; }
        public decimal ReedemedAmount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int DeleteStatus { get; set; }
    }
}
