//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponTry
    {
        public int CouponTryId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string CouponCode { get; set; }
        public Nullable<System.DateTime> TryDate { get; set; }
    }
}
