//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Mapping_Category_Mapping_Filter_Selection
    {
        public int Customer_Mapping_Category_Mapping_Filter_SelectionId { get; set; }
        public int CustomerId { get; set; }
        public int CategoryId { get; set; }
        public int Filter_TypeId { get; set; }
        public int SelectedItemId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpatedDate { get; set; }
        public int DeleteStatus { get; set; }
    }
}
