//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Add_To_Cart = new HashSet<Add_To_Cart>();
            this.ContactUsDetails = new HashSet<ContactUsDetail>();
            this.ContactUsDetails1 = new HashSet<ContactUsDetail>();
            this.Customer_Address = new HashSet<Customer_Address>();
            this.Customer_Feedback = new HashSet<Customer_Feedback>();
            this.Customer_Mapping_Scholarshippoints = new HashSet<Customer_Mapping_Scholarshippoints>();
            this.Customer_Package_Feedback_Rating = new HashSet<Customer_Package_Feedback_Rating>();
            this.Customer_Product_Rating = new HashSet<Customer_Product_Rating>();
            this.Customer_WishList = new HashSet<Customer_WishList>();
            this.Customers_Login = new HashSet<Customers_Login>();
            this.Orders = new HashSet<Order>();
            this.SchoolStuffDonations = new HashSet<SchoolStuffDonation>();
        }
    
        public int CustomerId { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public System.DateTime PasswordChangedDate { get; set; }
        public string ProfilePic { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int DeleteStatus { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DateOfBirth { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<System.DateTime> PointsExpiryDate { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public Nullable<int> StandardId { get; set; }
        public string ChildName { get; set; }
        public string StudentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Add_To_Cart> Add_To_Cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactUsDetail> ContactUsDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactUsDetail> ContactUsDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Address> Customer_Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Feedback> Customer_Feedback { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Mapping_Scholarshippoints> Customer_Mapping_Scholarshippoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Package_Feedback_Rating> Customer_Package_Feedback_Rating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Product_Rating> Customer_Product_Rating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_WishList> Customer_WishList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers_Login> Customers_Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolStuffDonation> SchoolStuffDonations { get; set; }
    }
}
