//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Replacement_Order
    {
        public int CustomerReplacementOrderId { get; set; }
        public int OrderId { get; set; }
        public int OrderReplacementId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int DeleteStatus { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> PackageId { get; set; }
    
        public virtual Package Package { get; set; }
        public virtual Order_Replacement Order_Replacement { get; set; }
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
