//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMappingStudent
    {
        public int CustomerMappingStudentId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public Nullable<int> StandardId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public int DeleteStatus { get; set; }
        public int CustomerId { get; set; }
        public string RollNo { get; set; }
        public string Division { get; set; }
        public string StudentId { get; set; }
    }
}
