//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSM
    {
        public int CustomerSMS_Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string MobileNumber { get; set; }
        public string SMS_Text { get; set; }
        public string SMS_ProviderId { get; set; }
        public string SMS_SendStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int DeleteStatus { get; set; }
    }
}
