//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Coupon
    {
        public int CustomerCouponId { get; set; }
        public int OrderId { get; set; }
        public int CouponId { get; set; }
        public int CouponUsedStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int DeleteStatus { get; set; }
    
        public virtual Coupon1 Coupon { get; set; }
        public virtual Order Order { get; set; }
    }
}
