//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Package_Feedback_Rating
    {
        public int CustomerPackageFeedbackRatingId { get; set; }
        public string Feedback { get; set; }
        public Nullable<double> Rating { get; set; }
        public int PackageId { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int DeleteStatus { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Package Package { get; set; }
    }
}
