//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class General_Specification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public General_Specification()
        {
            this.SubCategory_Mapping_GeneralSpecification = new HashSet<SubCategory_Mapping_GeneralSpecification>();
            this.Product_Mapping_GeneralSpecification = new HashSet<Product_Mapping_GeneralSpecification>();
        }
    
        public int GeneralSpecificationId { get; set; }
        public string SpecificationType { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int DeleteStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubCategory_Mapping_GeneralSpecification> SubCategory_Mapping_GeneralSpecification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Mapping_GeneralSpecification> Product_Mapping_GeneralSpecification { get; set; }
    }
}
