//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomePageContentMappingContent
    {
        public int HomePageContentMappingContentId { get; set; }
        public int HomePageContentId { get; set; }
        public int ProductOrSubCatOrBrandId { get; set; }
        public string ImagePath { get; set; }
        public string ExtraColumn1 { get; set; }
        public string ExtraColumn2 { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int DeleteStatus { get; set; }
    }
}
