//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Legal_And_Information
    {
        public int Legal_And_InformationId { get; set; }
        public string Header { get; set; }
        public string Text_Content { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int DeleteStatus { get; set; }
        public string FontAwesomeMobileIcon { get; set; }
        public string FontAwesomeWebIcon { get; set; }
    }
}
