//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationType
    {
        public int NotificationTypeId { get; set; }
        public string NotificationType1 { get; set; }
        public string AndroidLander { get; set; }
        public string iOSLander { get; set; }
        public string Header { get; set; }
        public string Footer { get; set; }
        public string SenderId { get; set; }
        public string ServerKey { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int DeleteStatus { get; set; }
    }
}
