//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Mapping_Transaction
    {
        public int OrderMappingTrasactionId { get; set; }
        public string TransactionRefNo { get; set; }
        public string PaymentMode { get; set; }
        public string PaymentId { get; set; }
        public string TransactionId { get; set; }
        public int OrderId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int DeleteStatus { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
