//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders_Mapping_Product_Package
    {
        public int OrderMappingProductPackageId { get; set; }
        public int OrderId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> PackageId { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int DeleteStatus { get; set; }
        public Nullable<double> DiscountPercent { get; set; }
        public Nullable<double> SGst { get; set; }
        public Nullable<double> CGst { get; set; }
        public Nullable<double> IGst { get; set; }
        public Nullable<decimal> SGstAmount { get; set; }
        public Nullable<decimal> CGstAmount { get; set; }
        public Nullable<decimal> IGstAmount { get; set; }
        public Nullable<decimal> ExcludingTaxPrice { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<double> SSCommissionPercent { get; set; }
        public Nullable<int> SchoolId { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Package Package { get; set; }
        public virtual Product Product { get; set; }
        public virtual School School { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
