//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Logistics_Delivery_Status
    {
        public int Order_Logistics_Delivery_StatusId { get; set; }
        public string awbno { get; set; }
        public string status_code { get; set; }
        public string status { get; set; }
        public string status_description { get; set; }
        public string remarks { get; set; }
        public string updated_date { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int DeleteStatus { get; set; }
    }
}
