//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderStatu()
        {
            this.CustomerOrder_Mapping_OrderStatus = new HashSet<CustomerOrder_Mapping_OrderStatus>();
        }
    
        public int OrderStatusId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int DeletStatus { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> ShippingStatusId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOrder_Mapping_OrderStatus> CustomerOrder_Mapping_OrderStatus { get; set; }
        public virtual Order Order { get; set; }
        public virtual ShippingStatu ShippingStatu { get; set; }
    }
}
