//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Customer_Coupon = new HashSet<Customer_Coupon>();
            this.Customer_Replacement_Order = new HashSet<Customer_Replacement_Order>();
            this.CustomerOrder_Mapping_OrderStatus = new HashSet<CustomerOrder_Mapping_OrderStatus>();
            this.CustomerOrder_Mapping_ShippingStatus = new HashSet<CustomerOrder_Mapping_ShippingStatus>();
            this.Order_Mapping_Courier = new HashSet<Order_Mapping_Courier>();
            this.Order_Mapping_Transaction = new HashSet<Order_Mapping_Transaction>();
            this.Order_Payment_Mode = new HashSet<Order_Payment_Mode>();
            this.Order_Price = new HashSet<Order_Price>();
            this.OrderStatus = new HashSet<OrderStatu>();
            this.Orders_Mapping_Product_Package = new HashSet<Orders_Mapping_Product_Package>();
            this.Status_Assign_Task = new HashSet<Status_Assign_Task>();
        }
    
        public int OrderId { get; set; }
        public int CustomerId { get; set; }
        public string Address { get; set; }
        public int OrderRedeem { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MobileNumber { get; set; }
        public string PinCode { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int DeleteStatus { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string Comment { get; set; }
        public Nullable<int> CustomerMappingStudentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Coupon> Customer_Coupon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Replacement_Order> Customer_Replacement_Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOrder_Mapping_OrderStatus> CustomerOrder_Mapping_OrderStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOrder_Mapping_ShippingStatus> CustomerOrder_Mapping_ShippingStatus { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Mapping_Courier> Order_Mapping_Courier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Mapping_Transaction> Order_Mapping_Transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Payment_Mode> Order_Payment_Mode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Price> Order_Price { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderStatu> OrderStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders_Mapping_Product_Package> Orders_Mapping_Product_Package { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Status_Assign_Task> Status_Assign_Task { get; set; }
    }
}
