//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package_Inventory_Mapping_Supplier_Mapping_School
    {
        public int Package_Inventory_Mapping_Supplier_Mapping_SchoolId { get; set; }
        public int SupplierId { get; set; }
        public int SchoolId { get; set; }
        public int PackageId { get; set; }
        public int InQuantity { get; set; }
        public int OutQuantity { get; set; }
        public int InStock { get; set; }
        public bool AcceptanceStatus { get; set; }
        public Nullable<System.DateTime> AcceptanceDate { get; set; }
        public Nullable<int> OrderId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int DeleteStatus { get; set; }
    }
}
