//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package_Mapping_School
    {
        public int PackageMappingSchoolId { get; set; }
        public int PackageId { get; set; }
        public int SchoolId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int DeleteStatus { get; set; }
        public Nullable<double> DiscountPercent { get; set; }
        public Nullable<double> DiscountPrice { get; set; }
        public Nullable<double> SchoolCommissionPercent { get; set; }
        public Nullable<double> SchoolCommissionPrice { get; set; }
        public bool ApplyDiscountOnLoosePurchaseFlag { get; set; }
    
        public virtual Package Package { get; set; }
        public virtual School School { get; set; }
    }
}
