//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package_Highlights
    {
        public int Package_HighlishtId { get; set; }
        public Nullable<int> PackageId { get; set; }
        public string Highlight { get; set; }
        public Nullable<bool> IsDeliveryHighlight { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeleteStatus { get; set; }
    }
}
