//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Package()
        {
            this.Add_To_Cart = new HashSet<Add_To_Cart>();
            this.Customer_Package_Feedback_Rating = new HashSet<Customer_Package_Feedback_Rating>();
            this.Customer_Replacement_Order = new HashSet<Customer_Replacement_Order>();
            this.Customer_WishList = new HashSet<Customer_WishList>();
            this.Orders_Mapping_Product_Package = new HashSet<Orders_Mapping_Product_Package>();
            this.Package_Commission_Supplier = new HashSet<Package_Commission_Supplier>();
            this.Package_Discount = new HashSet<Package_Discount>();
            this.Package_Images = new HashSet<Package_Images>();
            this.Package_Mapping_Board = new HashSet<Package_Mapping_Board>();
            this.Package_Mapping_BoardStandard = new HashSet<Package_Mapping_BoardStandard>();
            this.Package_Mapping_Products = new HashSet<Package_Mapping_Products>();
            this.Package_Mapping_School = new HashSet<Package_Mapping_School>();
            this.Package_Mapping_SchoolBoardStandard = new HashSet<Package_Mapping_SchoolBoardStandard>();
            this.Package_Mapping_Standard = new HashSet<Package_Mapping_Standard>();
        }
    
        public int PackageId { get; set; }
        public string PackageName { get; set; }
        public string ImagePath { get; set; }
        public string WarrantyPolicy { get; set; }
        public string ReplacementPolicy { get; set; }
        public Nullable<int> MaxAge { get; set; }
        public Nullable<int> MinAge { get; set; }
        public string PackageCode { get; set; }
        public Nullable<double> DiscountPercent { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int DeleteStatus { get; set; }
        public Nullable<double> SGst { get; set; }
        public Nullable<double> IGst { get; set; }
        public Nullable<double> CGst { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<double> SSCommissionPercent { get; set; }
        public decimal SchoolComission { get; set; }
        public bool IndividualPurchaseFlag { get; set; }
        public bool PurchaseAllowFlag { get; set; }
        public bool ApplyDiscountOnOnlyPackagePurchaseFlag { get; set; }
        public Nullable<System.DateTime> ExpectedDeliveryFrom { get; set; }
        public Nullable<System.DateTime> ExpectedDeliveryTo { get; set; }
        public string DeliveryNote { get; set; }
        public string Description { get; set; }
        public string Highlights { get; set; }
        public Nullable<bool> AllowChangeQty { get; set; }
        public Nullable<int> MinQty { get; set; }
        public Nullable<int> MaxQty { get; set; }
        public bool DisplayUnitPrice { get; set; }
        public bool ClubbedDelivery { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Add_To_Cart> Add_To_Cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Package_Feedback_Rating> Customer_Package_Feedback_Rating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Replacement_Order> Customer_Replacement_Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_WishList> Customer_WishList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders_Mapping_Product_Package> Orders_Mapping_Product_Package { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Package_Commission_Supplier> Package_Commission_Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Package_Discount> Package_Discount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Package_Images> Package_Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Package_Mapping_Board> Package_Mapping_Board { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Package_Mapping_BoardStandard> Package_Mapping_BoardStandard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Package_Mapping_Products> Package_Mapping_Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Package_Mapping_School> Package_Mapping_School { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Package_Mapping_SchoolBoardStandard> Package_Mapping_SchoolBoardStandard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Package_Mapping_Standard> Package_Mapping_Standard { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
