//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_Format_Mapping_Package
    {
        public int Payment_Format_Mapping_PackageId { get; set; }
        public int PaymentFormatId { get; set; }
        public Nullable<int> PackageId { get; set; }
        public Nullable<int> Package_Mapping_PackagesId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int DeleteStatus { get; set; }
    }
}
