//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaynimoPaymentSuccessDetail
    {
        public int PaymentSuccessDetailId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string merchantAdditionalDetails { get; set; }
        public string merchantTransactionIdentifier { get; set; }
        public string merchantTransactionRequestType { get; set; }
        public string responseType { get; set; }
        public string stringResponse { get; set; }
        public string transactionState { get; set; }
        public Nullable<int> bankSelectionCode { get; set; }
        public Nullable<double> amount { get; set; }
        public string statusCode { get; set; }
        public string identifier { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int DeleteStatus { get; set; }
    }
}
