//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publisher_Mapping_Brand
    {
        public int Publisher_Mapping_BrandId { get; set; }
        public int PublisherId { get; set; }
        public int BrandId { get; set; }
        public System.DateTime Createddate { get; set; }
        public System.DateTime Updateddate { get; set; }
        public bool DeleteStatus { get; set; }
    }
}
