//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School_Mapping_Supplier_Mapping_Settelment
    {
        public int School_Mapping_Supplier_Mapping_SettelmentId { get; set; }
        public int SchoolId { get; set; }
        public int SupplierId { get; set; }
        public double SetteledAmount { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int Payment_FormatId { get; set; }
        public int BankId { get; set; }
        public string TransactionRefNo { get; set; }
        public string Note { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int DeleteStatus { get; set; }
    }
}
