//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School_Mapping_ShippingCharges
    {
        public int School_Mapping_ShippingChargesId { get; set; }
        public int SchoolId { get; set; }
        public int SupplierId { get; set; }
        public int MinPrice { get; set; }
        public int MaxLimit { get; set; }
        public int ShippingCharge { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int DeleteStatus { get; set; }
        public int SchoolShippingCharges { get; set; }
    }
}
