//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School_Mapping_Board
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public School_Mapping_Board()
        {
            this.SchoolBoard_Mapping_Standard = new HashSet<SchoolBoard_Mapping_Standard>();
        }
    
        public int SchoolMappingBoardId { get; set; }
        public int SchoolId { get; set; }
        public int BoardId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int DeletStatus { get; set; }
    
        public virtual Board Board { get; set; }
        public virtual School School { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolBoard_Mapping_Standard> SchoolBoard_Mapping_Standard { get; set; }
    }
}
