//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School_Mapping_Standards
    {
        public int School_Mapping_StandardId { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public Nullable<int> StandardId { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public Nullable<int> StatusId { get; set; }
    }
}
