//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategory_Mapping_GeneralSpecification
    {
        public int SubCategoryMappingGeneralSpecificationId { get; set; }
        public int SubCategoryId { get; set; }
        public int GeneralSpecificationId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool DeleteStatus { get; set; }
    
        public virtual General_Specification General_Specification { get; set; }
    }
}
