//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubVendor
    {
        public int SubVendorId { get; set; }
        public string SubVendorName { get; set; }
        public string ContactNo { get; set; }
        public string EmailId { get; set; }
        public string UserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string DeleteStatus { get; set; }
    }
}
