//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierContactNumber
    {
        public int SupplierContactNumberId { get; set; }
        public int SupplierId { get; set; }
        public string ContactNumber { get; set; }
        public string Type { get; set; }
        public bool IsPrimary { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int DeleteStatus { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
