//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeacherMaster()
        {
            this.TeacherGradeMappings = new HashSet<TeacherGradeMapping>();
        }
    
        public int TeacherId { get; set; }
        public Nullable<int> T_schoolID { get; set; }
        public string salutaion { get; set; }
        public string TF_name { get; set; }
        public string TL_name { get; set; }
        public string Mobile_number { get; set; }
        public string Email_Id { get; set; }
        public string Password { get; set; }
        public Nullable<int> DeleteStatus { get; set; }
        public Nullable<int> RoleId { get; set; }
    
        public virtual Class1Roles Class1Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherGradeMapping> TeacherGradeMappings { get; set; }
    }
}
