//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherGradeMapping
    {
        public int MTeacherId { get; set; }
        public Nullable<int> MapTeacherId { get; set; }
        public Nullable<int> MapGradeID { get; set; }
    
        public virtual Standard Standard { get; set; }
        public virtual TeacherMaster TeacherMaster { get; set; }
    }
}
