//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempInventory
    {
        public int InventoryId { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public string SchoolName { get; set; }
        public Nullable<int> PackageId { get; set; }
        public string PackageName { get; set; }
        public Nullable<int> Inwards { get; set; }
        public Nullable<int> Outwards { get; set; }
        public Nullable<int> InStock { get; set; }
        public string AcceptanceStatus { get; set; }
        public string AcceptanceDate { get; set; }
    }
}
