//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VXpressStatu
    {
        public int VXpress_StatusId { get; set; }
        public string Code { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
    }
}
